[project]
name = "solax-ng"
version = "3.2.5"
description = "Solax inverter API client"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Khaled Eldoheiri", email = "khaled@eldoheiri.com" },
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp>=3.5.4,<4",
    "voluptuous>=0.11.5",
    "importlib_metadata>=3.6; python_version<'3.10'",
    "typing_extensions>=4.1.0; python_version<'3.11'",
]

[project.urls]
Homepage = "https://github.com/kdehairy/solax-ng"

[project.entry-points."solaxng.inverter"]
qvolt_hyb_g3_3p = "solaxng.inverters.qvolt_hyb_g3_3p:QVOLTHYBG33P"
x1 = "solaxng.inverters.x1:X1"
x1_boost = "solaxng.inverters.x1_boost:X1Boost"
x1_g4_series = "solaxng.inverters.x1_g4_series:X1G4Series"
x1_hybrid_gen4 = "solaxng.inverters.x1_hybrid_gen4:X1HybridGen4"
x1_mini = "solaxng.inverters.x1_mini:X1Mini"
x1_mini_v34 = "solaxng.inverters.x1_mini_v34:X1MiniV34"
x1_smart = "solaxng.inverters.x1_smart:X1Smart"
x1_lite_lv = "solaxng.inverters.x1_lite_lv:X1LiteLV"
x3 = "solaxng.inverters.x3:X3"
x3_hybrid_g4 = "solaxng.inverters.x3_hybrid_g4:X3HybridG4"
x3_ultra = "solaxng.inverters.x3_ultra:X3Ultra"
x3_mic_pro_g2 = "solaxng.inverters.x3_mic_pro_g2:X3MicProG2"
x3_v34 = "solaxng.inverters.x3_v34:X3V34"
x_hybrid = "solaxng.inverters.x_hybrid:XHybrid"
x3_evc = "solaxng.inverters.x3_evc:X3EVC"

[dependency-groups]
dev = [
    "black",
    "isort",
    "mypy",
    "flake8",
    "pylint",
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "pytest-httpserver",
]

[tool.uv.build-backend]
module-name = "solaxng"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
